dreamhost/veewee-definitions

Ubuntu-14.04-Trusty/definition.rb, Ubuntu-14.04-Trusty/gitlab.sh
Installs the gitlab omnibus pacakge. By default
this post script is disabled. It can be enabled
with post script cli flags at build time.
=> Gitlab post script for Ubuntu 14.04

Ubuntu-14.04-Trusty/dhc.sh
Sets up cloud.cfg to run scripts-per-* on cloud-init runs.
=> Setup scripts-per-* cloud init modules in trusty

Ubuntu-12.04-Precise/base.sh
This patch addresses a bug with installing some packages (namely
nfs-common) by cleaning out repo hashes before starting package
installs.
=> Clean out repo hashes before package installs

Ubuntu-12.04-Precise/dhc.sh
This patch addresses a bug where the dhc-user was not being created
properly for the Precise image.
=> Ensure dhc-user is create for Precise

Ubuntu-12.04-Precise/dhc.sh
The attempt to update the dhc.sh file for Precise has failed over the
last few iterations, so this patch simply pulls in the old dhc.sh file
that was used for the removed/renamed Precise image.
=> Restore old Precise image dhc.sh file

Fedora-21/definition.rb, Fedora-21/ks.cfg.erb
Fedora-21 is getting a different IP between kickstart and reboot.  This
patch sets a static IP so we don't have to rely on DHCP.  Also, a new
image source is selected as the other image source seemed to timeout
periodically.
=> Fix Fedora-21 automation

Fedora-21/dhc.sh
The only difference between this file and the default is the following line:
Before=plymouth-quit.service
If plymouth shuts down before cloud-init finishes, we lose all of the log messages we use for our tests.
=> cloud-init needs to run before Plymouth shuts down

Ubuntu-14.04/preseed.cfg.erb
This was changed for my personal machine at home and I forgot
to change it back.
=> don't use mirror.newdream.net for image installs

Centos-6.5/cleanup.sh, Centos-6.6/cleanup.sh, Centos-7.0/cleanup.sh, Fedora-20/cleanup.sh, Fedora-21/cleanup.sh
Yum caches which mirror it deems is fastest.  This patch removes this
cache from yum based distros so that the first time the user runs yum,
it will re-determine which mirror is the fastest, which could easily
have changed from image creation time to the time a VM is spun up from
this image.
=> Clear yum fastest mirror cache

Debian-7.0/base.sh, Debian-7.0/definition.rb, Debian-7.0/preseed.cfg.erb, Debian-8.0/base.sh, Debian-8.0/definition.rb, Debian-8.0/preseed.cfg.erb
This patch removes vagrant references in the veewee scripts for the
Debian 7.0 and 8.0 images.  These references shouldn't be needed as we
do things with generated values (for things like passwords and domains).
=> Remove vagrant references for Debian 7.0/8.0

Debian-8.0/dhc.sh
This patch points to the new location of passwd, which Debian-8.0 moved
from /bin/passwd to /usr/bin/passwd.
=> Debian-8.0 moved the location of passwd

Ubuntu-14.04/definition.rb, Ubuntu-14.04/dhc.sh
In an attempt to support both vfat and iso config drives, this patch
removes the fstab mount and leverages mountall (again).  There is a
known bug in mountall, but we'll address that later...
=> Ubuntu-14.04 re-use mountall magic

Ubuntu-14.04/dhc.sh
In order to address a stale mtab entry due to a cloudinit bug, this
patch removes any entry in /etc/mtab that is a vfat mount whose target
is under /tmp.
=> Ubuntu-14.04: Cleanup mtab

Ubuntu-14.04/dhc.sh
The previous commit attempted to cleanup by using sed to remove specific
entries from mtab.  However, there was a syntax error.  This patch
addresses the syntax error.
=> Ubuntun-14.04: fix mtab cleanup syntax

Centos-7.0/cleanup.sh, Centos-7.0/definition.rb, Centos-7.0/dhc.sh
This patch ensures that the EPEL repo is working on the Centos 7.0
image.  There were conflicting lines on dhc.sh and cleanup.sh.  dhc.sh
was installing epel (as was base.sh...) and cleanup.sh was removing it.
This patch assumes we do indeed want EPEL enabled and removes the
deletion of the repo from the cleanup.sh script.
=> Ensure EPEL is working for Centos7

Ubuntu-14.04/dhc.sh
Cloud-init has a great feature where it can reset your VMs hostname
unless you tell it to stop.  While we do want to set the hostname once,
we do not want to keep resetting it after every reboot.  This patch
disables the 'update_hostname' and 'update_etc_hosts' modules for
cloud-init, but leaves the 'set_hostname' module.  This should allow the
first boot to set the hostname and subsequent boots to leave the
hostname alone, should it change.
=> Ubuntu-14.04: only set hostname once

Ubuntu-14.04/definition.rb
After processsing the template, the preseed.cfg file is supposed to be
written to disk, then served via veewee.  However, it appears as though
ruby 2.1.0 is leaving the file handle open and not flushing to disk, so
the subsequent serving of preseed.cfg just serves a blank/empty file.
This patch adds an out.close call to ensure that the file is flushed to
disk.
=> Ubuntu-14.04: close compiled preseed file

Centos-6/cleanup.sh, Centos-6/dhc.sh, Centos-7/cleanup.sh, Centos-7/dhc.sh, Coreos/cleanup.sh, Coreos/dhc.sh, Debian-7.0/cleanup.sh, Debian-7.0/dhc.sh, Debian-8.0/cleanup.sh, Debian-8.0/dhc.sh, Debian-8.1/cleanup.sh, Debian-8.1/dhc.sh, Fedora-20/cleanup.sh, Fedora-20/dhc.sh, Fedora-21/cleanup.sh, Fedora-21/dhc.sh, Fedora-22/cleanup.sh, Fedora-22/dhc.sh, Ubuntu-12.04/cleanup.sh, Ubuntu-14.04/cleanup.sh
This patch removes the update_hostname and update_etc_hosts cloud-init
modules in order to allow for the user to provide a hostname and it not
get wiped out by cloud-init on the subsequent boot(s).  Also included is
a cleanup snippet that removes the hostname used during image buildtime
from the /etc/hosts file.
=> All: Remove update_hostname/etc_hosts modules

Ubuntu-12.04/dhc.sh
Our 14.04 image is using mountall to mount the config drive.  This seems
to be working now, as we've moved to ISO config drives.  Hoping this
fixes it for 12.04 as well.
=> Use mountall for 12.04

Centos-6/dhc.sh
Debian/Ubuntu do this better, but for Centos, we have to re-write the
grub file.  Since Centos-6 bumped their kernel, we too must bump our
dhc.sh script to point to the new kernel.
=> Centos-6: Bump kernel

Centos-6/definition.rb, Centos-6/reboot.sh
Growpart isn't working upon the first reboot, so try rebooting before
veewee is done doing it's thing.
=> Centos-6: add reboot

Debian-7.0/dhc.sh
This seems to be required now, otherwise resizefs wont install correctly
=> Debian-7.0: make sudo work without password

Debian-8.3/cleanup.sh
The attempt to disable dhcp during the initial boot failed.  Removing
this and seeing if 8.3 has better support for cloud-init, since 8.2.
was breaking.
=> Remove Debian-8.3 interface cleanup

Fedora-23/dhc.sh
Apparently, simply installing the cloud-init package does not enable the
service (upon boot).  Thus, we need to explicitly enable it during image
creation.
=> Fedora-23: explicitly enable cloud-init

Debian-8.3/cleanup.sh
Cloudinit does not like to properly configure interfaces that are already statically
configured.  Thus, we need to flatten the interfaces file to allow cloudinit to do its thing
=> debian-8.3: nuke interfaces

Debian-7.9/cleanup.sh, Fedora-22/cleanup.sh
Similar to the previous commit, we need cleanup intefaces for Debian-7.9 and Fedora-22.
=> nuke network configs

Debian-8.3/dhc.sh
Cloud-init doesn't seem to work with resolvconf based systems.  As such,
we need to set a valid nameserver ourselves.
=> Debian-8.3: set a nameserver manually

Debian-8.3/dhc.sh
Apparently 8.3 isn't using resolvconf? I guess I should read things
about stuff, but in the mean time, we'll dump our settings into the
correct config file.
=> Debian-8.3: put nameserver in correct file
